# Generated by Django 2.2.7 on 2019-11-07 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('central_lat', models.FloatField()),
                ('central_long', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('FMCG', (('Processed Food', 'Vinyl'), ('Beverages', 'CD'), ('Dry Goods', 'CD'), ('Prepared Meat', 'CD'), ('Cosmetics', 'CD'), ('Candy', 'CD'), ('Fresh Food', 'CD'), ('Frozen Good', 'CD'), ('Baked Goods', 'CD'), ('Electronics', 'CD'))), ('Media', (('vhs', 'VHS Tape'), ('dvd', 'DVD'), ('cd', 'CD'))), ('unknown', 'Unknown')], default='fmcg', max_length=500)),
                ('volume', models.FloatField(blank=True, default=100)),
                ('metric', models.CharField(blank=True, choices=[('Gram', 'Gram'), ('KiloGram', 'KiloGram'), ('metre', 'metre')], default='Gram', max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('central_lat', models.FloatField()),
                ('central_long', models.FloatField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('baker', 'baker'), ('barber', 'barber'), ('betting', 'betting'), ('baker', 'baker'), ('bookshop', 'bookshop'), ('boutique', 'boutique'), ('charity shop', 'charity shop'), ('grocer', 'grccer'), ('hardware', 'hardware'), ('stationary', 'stationary'), ('pharmacy', 'pharmacy'), ('supermarket', 'supermarket'), ('local', 'local'), ('off-licence', 'off-licence'), ('kiosk', 'kiosk'), ('others', 'others')], default='convinience', max_length=200)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField()),
                ('price', models.FloatField()),
                ('shelf', models.IntegerField()),
                ('facing', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_shop', to='main.Product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_in_shop', to='main.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='product', through='main.ProductInShop', to='main.Shop'),
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Region'),
        ),
    ]
