# Generated by Django 2.2.7 on 2019-11-07 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='volume',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='productinshop',
            old_name='availability',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='Region',
            new_name='region',
        ),
    ]
