# Generated by Django 2.2.7 on 2019-11-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20191107_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='productinshop',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='productinshop',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='metric',
            field=models.CharField(blank=True, choices=[('gram', 'Gram'), ('kilogram', 'KiloGram'), ('metre', 'Metre')], default='Gram', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('FMCG', (('processed food', 'Processed Food'), ('beverages', 'Beverages'), ('dry goods', 'Dry Goods'), ('prepared meat', 'Prepared Meat'), ('cosmetics', 'Cosmetics'), ('candy', 'Candy'), ('fresh food', 'Fresh Food'), ('frozen good', 'Frozen Goods'), ('baked goods', 'Baked Goods'), ('electronics', 'Electronics'))), ('Media', (('vhs', 'VHS Tape'), ('dvd', 'DVD'), ('cd', 'CD'))), ('unknown', 'Unknown')], default='fmcg', max_length=500),
        ),
        migrations.AlterField(
            model_name='shop',
            name='type',
            field=models.CharField(choices=[('baker', 'Baker'), ('barber', 'Barber'), ('betting', 'Betting'), ('baker', 'Baker'), ('bookshop', 'Bookshop'), ('boutique', 'Boutique'), ('charity shop', 'Charity Shop'), ('grocer', 'Grocer'), ('hardware', 'Hardware'), ('stationary', 'Stationary'), ('pharmacy', 'Pharmacy'), ('supermarket', 'Supermarket'), ('local', 'Local'), ('off-licence', 'Off-licence'), ('kiosk', 'Kiosk'), ('others', 'Others')], default='convinience', max_length=200),
        ),
    ]
